---
title: "methanobrevibacter_c1190_tree_comparison"
author: "Keri Burge"
date: "`r Sys.Date()`"
output: html_document
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(ape)
library(ggtree)
library(aplot)
library(viridis)
library(tidyverse)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

# Colors
```{r}
# Species clusters (5)
cluster_colors <- c("1188" = "#4292C6",
                      "1189" = "#A1D99B",
                      "1187" = "#FCB076",
                      "1190" = "#E794C1",
                      "Reference" = "lightgrey")


continent_colors <- c("Africa" = "#CC79A7",
                      "Asia" = "#97CE2F",
                      "Caribbean" = "#F09163",
                      "Europe" = "#9E9AC8",
                      "North America" = "#1ec1a7",
                      "Oceania" = "#098BD9",
                      "Reference" = "lightgrey")

mag_source_colors <- c("Ancient Human" = "#FFD5AF",
                       "Neanderthal" = "#FEEDA0",
                       "Modern non-industrial" = "#BCE1FF",
                       "Modern industrial" = "#EFB6D6",
                       "Non-human primate" = "#b2815e",
                       "Reference" = "lightgrey")

host_shapes <- c("Homo sapiens" = 16, "Homo sapiens neanderthalensis"  = 15, "Pan troglodytes schweinfurthii" = 17, "Reference" = 12, "Papio hamadryas" = 18)

```


Metadata
```{r}
metadata <- fread("./05-results/methanobrevibacter_metadata.tsv") %>%
  #filter(primary_cluster == 1188) %>%
  rename(Label = Bin) %>%
  rename(Bin = prepublication_bin) %>%
  #relocate(Bin, .before = Label) %>%
  mutate(Industrialization = if_else(Industrialization == "", "Reference", Industrialization)) %>%
  mutate(Industrialization = ifelse(str_detect(sample_host, "Homo sapiens neanderthalensis"), "Neanderthal", Industrialization)) %>%
  mutate(Industrialization = str_replace_all(Industrialization, "Non_industrial", "Modern non-industrial"),
         Industrialization = str_replace_all(Industrialization, "Industrial", "Modern industrial"),
         Industrialization = str_replace_all(Industrialization, "Ancient", "Ancient Human")) 
  
```

#No out group
##RAxML no out group
```{r}
tre_methanobrevibacter_c1190_no_outgroup <- ape::read.tree("./05-results/methanobrevibacter_c1190_scc.raxml.support")

tre_methanobrevibacter_c1190_no_outgroup$tip.label <- tre_methanobrevibacter_c1190_no_outgroup$tip.label %>%
  as.data.frame() %>%
  dplyr::rename(Bin = 1) %>%
  mutate(Bin = if_else(str_detect(Bin, "GC|refbinned"), Bin, 
                        str_replace_all(Bin, "-metaspades_00", ".bin.r.") %>%
                        str_replace_all("-metaspades_0", ".bin.r.") %>%
                        str_replace_all("-metaspades", ".bin.r.") %>%
                        str_replace_all("-megahit_00", ".bin.r.") %>%
                        str_replace_all("-megahit_0", ".bin.r.") %>%
                        str_replace_all("-megahit_", ".bin.r.") %>%
                        str_replace_all("_", ""))) %>%
  inner_join(metadata, by = "Bin") %>%
  select(Label) %>%
  pull(Label)

filtered_metadata <- tre_methanobrevibacter_c1190_no_outgroup$tip.label %>%
  as.data.frame() %>%
  dplyr::rename(Label = 1) %>%
  inner_join(., metadata, by = "Label")

#Root from MAD rooting - ERSX0005001-megahit_029

tre_methanobrevibacter_c1190_no_outgroup <- root(tre_methanobrevibacter_c1190_no_outgroup, outgroup = "ERS26854150.bin.r.29")

methanobrevibacter_c1190_no_outgroup <- ggtree(tre_methanobrevibacter_c1190_no_outgroup, ladderize = T)

methanobrevibacter_c1190_raxml_no_outgroup_tree <- methanobrevibacter_c1190_no_outgroup %<+% filtered_metadata + 
  geom_tippoint(aes(color = log_age, shape = sample_host), size = 5) +
  scale_size_continuous(limits = c(0,3)) +
  theme(legend.position="right") + 
  #scale_color_viridis_c(option = "inferno", name = "Age (BP) (log10)", begin = 0.2, end = 1) +
  scale_color_viridis_c(option = "mako", name = "Age (BP) (log10)", direction = -1, limits = c(0.845098, 5.008600)) +
  scale_shape_manual(values = host_shapes, name = "Sample Host") +
  geom_treescale(x = 0, y = 5, width = 0.005, fontsize = 4) +
  geom_nodelab(aes(label = ifelse(as.numeric(label) > 50, label, "")), size = 2, hjust = -0.1) +
  guides(shape = guide_legend(override.aes = list(size = 3))) +
  geom_tiplab(size = 2, hjust = -0.1)

methanobrevibacter_c1190_raxml_no_outgroup_tree
```


##CASTER no out group
```{r}
methanobrevibacter_c1190_caster_no_outgroup <- ape::read.tree("./05-results/methanobrevibacter_c1190_no_outgroup.caster.nwk")


methanobrevibacter_c1190_caster_no_outgroup$tip.label <- methanobrevibacter_c1190_caster_no_outgroup$tip.label %>%
  as.data.frame() %>%
  dplyr::rename(Bin = 1) %>%
  mutate(Bin = if_else(str_detect(Bin, "GC|refbinned"), Bin, 
                        str_replace_all(Bin, "-metaspades_00", ".bin.r.") %>%
                        str_replace_all("-metaspades_0", ".bin.r.") %>%
                        str_replace_all("-metaspades", ".bin.r.") %>%
                        str_replace_all("-megahit_00", ".bin.r.") %>%
                        str_replace_all("-megahit_0", ".bin.r.") %>%
                        str_replace_all("-megahit_", ".bin.r.") %>%
                        str_replace_all("_", ""))) %>%
  inner_join(metadata, by = "Bin") %>%
  select(Label) %>%
  pull(Label)


methanobrevibacter_c1190_caster_no_outgroup <- root(methanobrevibacter_c1190_caster_no_outgroup, outgroup = "ERS26854150.bin.r.29")

methanobrevibacter_c1190_caster_tree <- ggtree(methanobrevibacter_c1190_caster_no_outgroup, ladderize = T)


methanobrevibacter_c1190_caster_no_outgroup <- methanobrevibacter_c1190_caster_tree %<+% filtered_metadata + 
  geom_tippoint(aes(color = log_age, shape = sample_host), size = 5) +
  scale_size_continuous(limits = c(0,3)) +
  theme(legend.position="right") + 
  #scale_color_viridis_c(option = "inferno", name = "Age (BP) (log10)", begin = 0.2, end = 1) +
  scale_color_viridis_c(option = "mako", name = "Age (BP) (log10)", direction = -1, limits = c(0.845098, 5.008600)) +
  scale_shape_manual(values = host_shapes, name = "Sample Host") +
  geom_treescale(x = 0, y = 5, width = 0.005, fontsize = 4) +
  geom_nodelab(aes(label = ifelse(as.numeric(label) > 50, label, "")), size = 2, hjust = -0.1) +
  guides(shape = guide_legend(override.aes = list(size = 3))) +
  geom_tiplab(size = 2, hjust = -0.1)

methanobrevibacter_c1190_caster_no_outgroup


```


##Tanglegram
```{r}
#Ladderize the trees
t1_ladder <- ladderize(tre_methanobrevibacter_c1190_no_outgroup) #RAxML tree
t2_ladder <- ladderize(methanobrevibacter_c1190_caster_no_outgroup) #CASTER tree

association <- cbind(t1_ladder$tip.label, t1_ladder$tip.label)

#Metadata colors
tip_order <- data.frame(Bin = association[,2])
matched_meta <- merge(tip_order, filtered_metadata, by = "Bin", all.x = TRUE, sort = FALSE)

#Re-sort to match original tip_order exactly (merge can scramble rows)
matched_meta <- matched_meta[match(tip_order$Bin, matched_meta$Bin), ]


#Define colors for metadata
unique_continent <- unique(matched_meta$Continent)
unique_host <- unique(matched_meta$Industrialization)

host_colors <- c("Ancient Human" = "#FFD5AF",
                       "Neanderthal" = "#FEEDA0",
                       "Modern non-industrial" = "#BCE1FF",
                       "Modern industrial" = "#EFB6D6",
                       "Non-human primate" = "#b2815e",
                       "Reference" = "lightgrey")


#Assign a color to every tip based on its metadata
line_cols_host <- host_colors[matched_meta$Industrialization]
line_cols_continent <- continent_colors[matched_meta$Continent]

t1_fixed <- compute.brlen(t1_ladder, 1)
t2_fixed <- compute.brlen(t2_ladder, 1)


ape::cophyloplot(
  t1_fixed,
  t2_fixed,
  assoc = association,
  show.tip.label = T,
  use.edge.length = FALSE, # This is key: it forces branches to the edge
  space = 250, # Adjust this to move trees even closer
  gap =25,
  length.line = 0,
  col = line_cols_host,
  lwd = 1.5)


ape::cophyloplot(
  t1_fixed,
  t2_fixed,
  assoc = association,
  show.tip.label = T,
  use.edge.length = FALSE, # This is key: it forces branches to the edge
  space = 250, # Adjust this to move trees even closer
  gap = 25,
  length.line = 0,
  col = line_cols_continent,
  lwd = 1.5)



```

```{r}
#run in console to save tanglegram
svg(file = "",
    width = 12,
    height = 8)

ape::cophyloplot(
  t1_fixed,
  t2_fixed,
  assoc = association,
  show.tip.label = T,
  use.edge.length = FALSE, # This is key: it forces branches to the edge
  space = 250, # Adjust this to move trees even closer
  gap =25,
  length.line = 0,
  col = line_cols_host,
  lwd = 1.5)

dev.off()

```


#Out group
##RAxML with out group
```{r}
tre_methanobrevibacter_c1190_w_outgroup <- ape::read.tree("./05-results/methanobrevibacter_c1190_w_outgroup_scc.raxml.support")

tre_methanobrevibacter_c1190_w_outgroup$tip.label <- tre_methanobrevibacter_c1190_w_outgroup$tip.label %>%
  as.data.frame() %>%
  dplyr::rename(Bin = 1) %>%
  mutate(Bin = if_else(str_detect(Bin, "GC|refbinned"), Bin, 
                        str_replace_all(Bin, "-metaspades_00", ".bin.r.") %>%
                        str_replace_all("-metaspades_0", ".bin.r.") %>%
                        str_replace_all("-metaspades", ".bin.r.") %>%
                        str_replace_all("-megahit_00", ".bin.r.") %>%
                        str_replace_all("-megahit_0", ".bin.r.") %>%
                        str_replace_all("-megahit_", ".bin.r.") %>%
                        str_replace_all("_", ""))) %>%
  left_join(metadata, by = "Bin") %>%
  select(Label) %>%
  pull(Label)

filtered_metadata <- tre_methanobrevibacter_c1190_w_outgroup$tip.label %>%
  as.data.frame() %>%
  dplyr::rename(Label = 1) %>%
  inner_join(., metadata, by = "Label")

#Root with M. oralis
tre_methanobrevibacter_c1190_w_out <- root(tre_methanobrevibacter_c1190_w_outgroup, outgroup = "GCF_001639275.1_ASM163927v1_genomic")

#tre_methanobrevibacter_c1190_w_outgroup_midpoint <- phangorn::midpoint(tre_methanobrevibacter_c1190_w_outgroup)

#tre_methanobrevibacter_c1190_w_outgroup_midpoint_dropped <- drop.tip(tre_methanobrevibacter_c1190_w_outgroup_midpoint, "GCF_001639275.1_ASM163927v1_genomic")

methanobrevibacter_c1190_w_outgroup_midpoint_dropped_tree <- ggtree(tre_methanobrevibacter_c1190_w_outgroup_midpoint_dropped, ladderize = T)

methanobrevibacter_c1190_raxml_w_outgroup_tree <- methanobrevibacter_c1190_w_outgroup_midpoint_dropped_tree %<+% filtered_metadata + 
  geom_tippoint(aes(color = log_age, shape = sample_host), size = 5) +
  scale_size_continuous(limits = c(0,3)) +
  theme(legend.position="right") + 
  #scale_color_viridis_c(option = "inferno", name = "Age (BP) (log10)", begin = 0.2, end = 1) +
  scale_color_viridis_c(option = "mako", name = "Age (BP) (log10)", direction = -1, limits = c(0.845098, 5.008600)) +
  scale_shape_manual(values = host_shapes, name = "Sample Host") +
  geom_treescale(x = 0, y = 5, width = 0.005, fontsize = 4) +
  geom_nodelab(aes(label = ifelse(as.numeric(label) > 50, label, "")), size = 2, hjust = -0.1) +
  guides(shape = guide_legend(override.aes = list(size = 3))) +
  geom_tiplab(size = 2, hjust = -0.1)

methanobrevibacter_c1190_raxml_w_outgroup_tree
```


##CASTER with out group
```{r}
methanobrevibacter_c1190_caster_w_outgroup <- ape::read.tree("./05-results/methanobrevibacter_c1190_w_outgroup.caster.nwk")


methanobrevibacter_c1190_caster_w_outgroup$tip.label <- methanobrevibacter_c1190_caster_w_outgroup$tip.label %>%
  as.data.frame() %>%
  dplyr::rename(Bin = 1) %>%
  mutate(Bin = if_else(str_detect(Bin, "GC|refbinned"), Bin, 
                        str_replace_all(Bin, "-metaspades_00", ".bin.r.") %>%
                        str_replace_all("-metaspades_0", ".bin.r.") %>%
                        str_replace_all("-metaspades", ".bin.r.") %>%
                        str_replace_all("-megahit_00", ".bin.r.") %>%
                        str_replace_all("-megahit_0", ".bin.r.") %>%
                        str_replace_all("-megahit_", ".bin.r.") %>%
                        str_replace_all("_", ""))) %>%
  left_join(metadata, by = "Bin") %>%
  select(Label) %>%
  pull(Label)


methanobrevibacter_c1190_caster_w_outgroup <- root(methanobrevibacter_c1190_caster_w_outgroup, outgroup = "GCF_001639275.1_ASM163927v1_genomic")

methanobrevibacter_c1190_caster_tree <- ggtree(methanobrevibacter_c1190_caster_w_outgroup, ladderize = T)


methanobrevibacter_c1190_caster_w_outgroup <- methanobrevibacter_c1190_caster_tree %<+% filtered_metadata + 
  geom_tippoint(aes(color = log_age, shape = sample_host), size = 5) +
  scale_size_continuous(limits = c(0,3)) +
  theme(legend.position="right") + 
  #scale_color_viridis_c(option = "inferno", name = "Age (BP) (log10)", begin = 0.2, end = 1) +
  scale_color_viridis_c(option = "mako", name = "Age (BP) (log10)", direction = -1, limits = c(0.845098, 5.008600)) +
  scale_shape_manual(values = host_shapes, name = "Sample Host") +
  geom_treescale(x = 0, y = 5, width = 0.005, fontsize = 4) +
  geom_nodelab(aes(label = ifelse(as.numeric(label) > 50, label, "")), size = 2, hjust = -0.1) +
  guides(shape = guide_legend(override.aes = list(size = 3))) +
  geom_tiplab(size = 2, hjust = -0.1)

methanobrevibacter_c1190_caster_w_outgroup


```


##Tanglegram
```{r}
#Ladderize the trees
t1_ladder <- ladderize(tre_methanobrevibacter_c1190_w_out) #RAxML tree
t2_ladder <- ladderize(methanobrevibacter_c1190_caster_w_outgroup) #CASTER tree

association <- cbind(t1_ladder$tip.label, t1_ladder$tip.label)

#Metadata colors
tip_order <- data.frame(Bin = association[,2])
matched_meta <- merge(tip_order, filtered_metadata, by = "Bin", all.x = TRUE, sort = FALSE)

#Re-sort to match original tip_order exactly (merge can scramble rows)
matched_meta <- matched_meta[match(tip_order$Bin, matched_meta$Bin), ]


#Define colors for metadata
unique_continent <- unique(matched_meta$Continent)
unique_host <- unique(matched_meta$Industrialization)

host_colors <- c("Ancient Human" = "#FFD5AF",
                       "Neanderthal" = "#FEEDA0",
                       "Modern non-industrial" = "#BCE1FF",
                       "Modern industrial" = "#EFB6D6",
                       "Non-human primate" = "#b2815e",
                       "Reference" = "lightgrey")


#Assign a color to every tip based on its metadata
line_cols_host <- host_colors[matched_meta$Industrialization]
line_cols_continent <- continent_colors[matched_meta$Continent]

t1_fixed <- compute.brlen(t1_ladder, 1)
t2_fixed <- compute.brlen(t2_ladder, 1)


ape::cophyloplot(
  t1_fixed,
  t2_fixed,
  assoc = association,
  show.tip.label = T,
  use.edge.length = FALSE, # This is key: it forces branches to the edge
  space = 250, # Adjust this to move trees even closer
  gap =25,
  length.line = 0,
  col = line_cols_host,
  lwd = 1.5)


ape::cophyloplot(
  t1_fixed,
  t2_fixed,
  assoc = association,
  show.tip.label = T,
  use.edge.length = FALSE, # This is key: it forces branches to the edge
  space = 250, # Adjust this to move trees even closer
  gap = 25,
  length.line = 0,
  col = line_cols_continent,
  lwd = 1.5)



```

```{r}
#run in console to save tanglegram
svg(file = "",
    width = 12,
    height = 8)

ape::cophyloplot(
  t1_fixed,
  t2_fixed,
  assoc = association,
  show.tip.label = T,
  use.edge.length = FALSE, # This is key: it forces branches to the edge
  space = 250, # Adjust this to move trees even closer
  gap =25,
  length.line = 0,
  col = line_cols_host,
  lwd = 1.5)

dev.off()

```




